dist: trusty
sudo: required

language: python
python:
  - 3.4
  - 3.5
  - 3.6

env:
  global:
    - PIP_DOWNLOAD_CACHE="pip_download_cache"
  matrix:
    - DJANGO_VERSION=">=1.8,<1.9"
    - DJANGO_VERSION=">=1.9,<1.10"
    - DJANGO_VERSION=">=1.10,<1.11"

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

services:
  - postgresql
  - neo4j

install:
  - pip install -Uq pip setuptools coveralls
  - pip install "Django${DJANGO_VERSION}"
  - python setup.py clean build install

script:
  - python setup.py test

after_success: coveralls

matrix:
  fast_finish: true

notifications:
  email: false
