dist: trusty
sudo: required
language: python
python:
  - 3.4
  - 3.5
  - 3.6

env:
  global:
    - NEO4J_VERSION="3.0"
    - PIP_DOWNLOAD_CACHE="pip_download_cache"
  matrix:
    - DJANGO_VERSION=">=1.10,<1.11"
    - DJANGO_VERSION=">=1.11,<2.0"

addons:
  apt:
    sources:
      - sourceline: 'ppa:cleishm/neo4j'
    packages:
      - build-essential
      - libcypher-parser-dev

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

services:
  - postgresql
  - docker

before_install:
  - docker run -d --name neo4j -p 7687:7687 -e NEO4J_AUTH=none neo4j:$NEO4J_VERSION
  - docker ps -a

install:
  - pip install -Uq pip setuptools coveralls
  - pip install "Django${DJANGO_VERSION}"
  - python setup.py clean build install

script:
  - python setup.py test

after_success: coveralls

after_script:
  - docker rm -f neo4j

matrix:
  fast_finish: true

notifications:
  email: false
