language: python
python:
  - 3.4
  - 3.5

cache:
  apt: true
  pip: true
  directories:
    - pip_download_cache

env:
  global:
    - NEO4J_VERSION="3.1.1"
    - PIP_DOWNLOAD_CACHE="pip_download_cache"
  matrix:
    - DJANGO_VERSION=">=1.8,<1.9"
    - DJANGO_VERSION=">=1.9,<1.10"
    - DJANGO_VERSION=">=1.10,<1.11"

jdk:
  - oraclejdk8

before_install:
  - mkdir -p $PIP_DOWNLOAD_CACHE
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start

install:
  - pip install tox
  - pip install coveralls
  - pip install "Django${DJANGO_VERSION}"

after_success:
  coveralls

script:
  - python setup.py test

# Required for neo4j to work
#dist: trusty
#sudo: false
#
#services:
#  - neo4j


notifications:
  email: false
