language: python
python:
  - 3.4
  - 3.5

cache:
  apt: true
  pip: true
  directories:
    - pip_download_cache

before_install:
  - mkdir -p $PIP_DOWNLOAD_CACHE

install:
  - pip install tox
  - pip install coveralls
  - pip install "Django${DJANGO_VERSION}"

after_success:
  coveralls

script:
  - python setup.py test

env:
  global:
    - PIP_DOWNLOAD_CACHE="pip_download_cache"
  matrix:
    - DJANGO_VERSION=">=1.8,<1.9"
    - DJANGO_VERSION=">=1.9,<1.10"
    - DJANGO_VERSION=">=1.10,<1.11"

# Required for neo4j to work
sudo: required
dist: trusty

services:
  - neo4j

notifications:
  email: false
