version: '2'
services:
  neo4j:
    image: neo4j:latest
    volumes:
      - ./.docker-data/neo4j:/data
    environment:
      - NEO4J_AUTH=none
    ports:
      - "7474:7474"
      - "7687:7687"
  postgres:
    image: postgres:latest
    volumes:
      - .docker-data/postgresql:/var/lib/postgresql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"

