# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 09:50
from __future__ import unicode_literals

import chemtrails.contrib.permissions.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', chemtrails.contrib.permissions.fields.ArrayChoiceField(base_field=models.CharField(blank=True, max_length=100), blank=True, choices=[(['ACCESSRULE', 'PERMISSIONS', 'ACCESSRULE_PERMISSIONS'], 'AccessRule'), (['AUTHOR', 'AUTHORS', 'BOOK', 'USER'], 'Author'), (['AUTHOR', 'BOOK'], 'Book_authors'), (['BOOK', 'BOOKS', 'BESTSELLER', 'STORE', 'BESTSELLER_STORES', 'TAGS', 'AUTHORS', 'PUBLISHER'], 'Book'), (['BOOK', 'PUBLISHER'], 'Publisher'), (['BOOK', 'STORE'], 'Store_books'), (['CONTENT_TYPE', 'CONTENT_TYPE_SET_FOR_TAG', 'PERMISSION', 'LOGENTRY'], 'ContentType'), (['GROUP', 'USER'], 'User_groups'), (['GROUP', 'USER_SET', 'PERMISSIONS', 'GROUPS'], 'Group'), (['LOGENTRY', 'CONTENT_TYPE', 'USER'], 'LogEntry'), (['PERMISSION', 'ACCESSRULE'], 'AccessRule_permissions'), (['PERMISSION', 'GROUP'], 'Group_permissions'), (['PERMISSION', 'PERMISSIONS', 'ACCESSRULE_PERMISSIONS', 'USER_SET', 'GROUP', 'CONTENT_TYPE', 'USER_PERMISSIONS'], 'Permission'), (['PERMISSION', 'USER'], 'User_user_permissions'), (['STORE', 'BOOKS', 'BESTSELLER', 'BESTSELLER_STORES'], 'Store'), (['TAGS', 'CONTENT_TYPE', 'CONTENT_TYPE_SET_FOR_TAG'], 'Tag'), (['USER', 'USER_SET', 'LOGENTRY', 'USER_PERMISSIONS', 'GROUPS', 'AUTHOR'], 'User')], size=None)),
                ('target', chemtrails.contrib.permissions.fields.ArrayChoiceField(base_field=models.CharField(blank=True, max_length=100), blank=True, choices=[(['ACCESSRULE', 'PERMISSIONS', 'ACCESSRULE_PERMISSIONS'], 'AccessRule'), (['AUTHOR', 'AUTHORS', 'BOOK', 'USER'], 'Author'), (['AUTHOR', 'BOOK'], 'Book_authors'), (['BOOK', 'BOOKS', 'BESTSELLER', 'STORE', 'BESTSELLER_STORES', 'TAGS', 'AUTHORS', 'PUBLISHER'], 'Book'), (['BOOK', 'PUBLISHER'], 'Publisher'), (['BOOK', 'STORE'], 'Store_books'), (['CONTENT_TYPE', 'CONTENT_TYPE_SET_FOR_TAG', 'PERMISSION', 'LOGENTRY'], 'ContentType'), (['GROUP', 'USER'], 'User_groups'), (['GROUP', 'USER_SET', 'PERMISSIONS', 'GROUPS'], 'Group'), (['LOGENTRY', 'CONTENT_TYPE', 'USER'], 'LogEntry'), (['PERMISSION', 'ACCESSRULE'], 'AccessRule_permissions'), (['PERMISSION', 'GROUP'], 'Group_permissions'), (['PERMISSION', 'PERMISSIONS', 'ACCESSRULE_PERMISSIONS', 'USER_SET', 'GROUP', 'CONTENT_TYPE', 'USER_PERMISSIONS'], 'Permission'), (['PERMISSION', 'USER'], 'User_user_permissions'), (['STORE', 'BOOKS', 'BESTSELLER', 'BESTSELLER_STORES'], 'Store'), (['TAGS', 'CONTENT_TYPE', 'CONTENT_TYPE_SET_FOR_TAG'], 'Tag'), (['USER', 'USER_SET', 'LOGENTRY', 'USER_PERMISSIONS', 'GROUPS', 'AUTHOR'], 'User')], size=None)),
                ('cypher', models.TextField(blank=True, help_text='cypher query for ths access rule.', verbose_name='cypher query')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this access rule.', related_name='accessrule_permissions', related_query_name='accessrule', to='auth.Permission', verbose_name='access rule permissions')),
            ],
        ),
    ]
