# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 20:06
from __future__ import unicode_literals

import chemtrails.contrib.permissions.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', chemtrails.contrib.permissions.fields.ArrayChoiceField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None)),
                ('target', chemtrails.contrib.permissions.fields.ArrayChoiceField(base_field=models.CharField(blank=True, max_length=100), blank=True, size=None)),
                ('action', models.CharField(blank=True, choices=[('add', 'Add'), ('change', 'Change'), ('delete', 'Delete')], max_length=20)),
            ],
        ),
    ]
