# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemtrails_permissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrule',
            options={'ordering': ('ctype_target', '-created')},
        ),
    ]
