# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 12:08
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemtrails_permissions', '0002_accessrule_ordering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrule',
            name='query',
        ),
        migrations.AddField(
            model_name='accessrule',
            name='relation_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True), default=[], help_text='Required relation types for generating a Cypher path.', size=None, verbose_name='relation types'),
        ),
    ]
