# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-10 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemtrails_permissions', '0002_accessrule_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrule',
            name='with_relation_props',
            field=models.BooleanField(choices=[(True, 'Enabled'), (False, 'Disabled')], default=True, help_text='If enabled, relationships will be matched by certain properties, such as type (ForeignKey, ManyToManyField, etc), else only relationship labels will be used.', verbose_name='with relationship properties'),
        ),
    ]
