# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemtrails_permissions', '0003_accessrule_relation_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrule',
            name='requires_staff',
            field=models.BooleanField(default=False, help_text='Requires user which should have permissions evaluated to be a staff user.'),
        ),
    ]
