# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-02 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemtrails_permissions', '0004_accessrule_requires_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrule',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
        ),
    ]
