# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_book_view_book_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='test',
            field=models.BooleanField(default=False),
        ),

    ]
#
