# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_remove_author_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='publishers',
            field=models.ManyToManyField(to='testapp.Publisher'),
        ),
    ]
